[package]
name = "salt_map"
version = "0.1.0"
authors = ["maya"]

[dependencies]
blake2-rfc = "0.2.18"
chashmap = "2.2.0"
memmap = "0.7.0"
rayon = "1.0.2"
rust-argon2 = "0.3.0"
rust_sodium = "0.10.1"
tiny-keccak = "1.4.2"
